[project]
name = "numbat"
version = "0.1.0"
description = "Software to run the NuMBAT experiment."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "syncboard",
    "SynthNVProDriver",
    "atik-python-sdk",
    "matplotlib>=3.8",
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.uv.sources]
syncboard = { path = "drivers/sync_board", editable = true }
SynthNVProDriver = { path = "drivers/SynthNVProDriver", editable = true }
atik-python-sdk = { path = "vendor/atik/Atik_Python_SDK-1.5.1-py3-none-any.whl" }
